////////////////////////////////OptionsWindow//////////////////////////////////
package cu.trustGrapher;

import cu.trustGrapher.eventplayer.EventPlayer;
import utilities.ChatterBox;
import utilities.PropertyManager;

/**
 * Description
 * @author Andrew O'Hara
 */
public class OptionsWindow extends javax.swing.JFrame {
    public static final String DELAY = "delay";
    private EventPlayer eventThread;
    private PropertyManager config;

//////////////////////////////////Constructor///////////////////////////////////
    public OptionsWindow(PropertyManager config, EventPlayer eventThread) {
        config.loadPropertyFile();
        this.config = config;        
        this.eventThread = eventThread;
        initComponents();
        setVisible(false);
    }

///////////////////////////////////Methods//////////////////////////////////////
    public void showWindow(){
        if (!config.containsKey(DELAY)){
            config.setProperty(DELAY, "" + EventPlayer.DEFAULT_DELAY);
            config.save();
        }
        if (config.getProperty(DELAY).equals("" + EventPlayer.DEFAULT_DELAY)){
            defaultDelayButton.doClick();
            delayField.setText("");
        }else{
            customDelayButton.doClick();
            delayField.setText(config.getProperty(DELAY));
        }
        setVisible(true);
    }

/////////////////////////////////GUI Components/////////////////////////////////
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        defaultDelayButton = new javax.swing.JRadioButton();
        customDelayButton = new javax.swing.JRadioButton();
        delayLabel = new javax.swing.JLabel();
        delayField = new javax.swing.JTextField();
        msLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setTitle("TrustGrapher Options");

        buttonGroup1.add(defaultDelayButton);
        defaultDelayButton.setSelected(true);
        defaultDelayButton.setText("Default Delay (250 ms)");
        defaultDelayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultDelayButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(customDelayButton);
        customDelayButton.setText("Custom Delay");
        customDelayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customDelayButtonActionPerformed(evt);
            }
        });

        delayLabel.setText("Delay: ");
        delayLabel.setEnabled(false);

        delayField.setColumns(4);
        delayField.setText("250");
        delayField.setEnabled(false);

        msLabel.setText("ms");
        msLabel.setEnabled(false);

        jLabel1.setText("Modify delay between each tick:");

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(delayLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msLabel)
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(customDelayButton)
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(defaultDelayButton)
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(okButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(defaultDelayButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customDelayButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delayLabel)
                    .addComponent(delayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(msLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void defaultDelayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultDelayButtonActionPerformed
    delayLabel.setEnabled(false);
    delayField.setEnabled(false);
    msLabel.setEnabled(false);
}//GEN-LAST:event_defaultDelayButtonActionPerformed

private void customDelayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customDelayButtonActionPerformed
    delayLabel.setEnabled(true);
    delayField.setEnabled(true);
    msLabel.setEnabled(true);
}//GEN-LAST:event_customDelayButtonActionPerformed

private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
    try{
        int delay = EventPlayer.DEFAULT_DELAY;
        if (customDelayButton.isSelected()){
            delay = Integer.parseInt(delayField.getText());
            if (delay < 1 || delay > 9000){
                throw new NumberFormatException();
            }
        }
        if (eventThread != null){
            eventThread.setDelay(delay);
        }
        config.setProperty(DELAY, "" + delay);
        config.save();
        setVisible(false);
    }catch (NumberFormatException ex){
        ChatterBox.alert("You must enter an integer between 1 and 9 000");
    }
}//GEN-LAST:event_okButtonActionPerformed

private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    setVisible(false);
}//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JRadioButton customDelayButton;
    private javax.swing.JRadioButton defaultDelayButton;
    private javax.swing.JTextField delayField;
    private javax.swing.JLabel delayLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel msLabel;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
////////////////////////////////////////////////////////////////////////////////
