//////////////////////////////////AreWeThereYet/////////////////////////////////
package aohara.utilities;

/**
 * A progress bar embedded or in a JDialog
 * @author Andrew O'Hara
 */
public class AreWeThereYet extends javax.swing.JDialog {

    private boolean embed, loading;

//////////////////////////////////Constructor///////////////////////////////////
    public AreWeThereYet(java.awt.Component parent) {
        this.setLocationRelativeTo(parent);
        embed = false;
        loading = false;
        initComponents();
    }

//////////////////////////////////Accessors/////////////////////////////////////
    public java.awt.Container embed() {
        embed = true;
        return getContentPane();
    }

    public boolean loading() {
        return loading;
    }

///////////////////////////////////Methods//////////////////////////////////////
    public void loadingStarted(int numberLines, String whatIsLoading) {
        loading = true;
        progressBar.setMinimum(0);
        progressBar.setMaximum(numberLines);
        progressBar.setValue(0);
        progressBar.setString("0%");
        progressBar.setStringPainted(true);
        label.setText("Loading " + whatIsLoading);
        if (embed) {
            getContentPane().setVisible(true);
        } else {
            setVisible(true);
        }
    }

    public void loadingProgress(int lineNumber) {
        progressBar.setValue(lineNumber);
        progressBar.setString((String.format("%.3g%n", progressBar.getPercentComplete() * 100)) + "%");
    }

    public void loadingProgress() {
        loadingProgress(progressBar.getValue() + 1);
    }

    public void loadingComplete() {
        try {
            Thread.currentThread().sleep(200);
        } catch (InterruptedException ex) {
        }
        loading = false;
        label.setText("Loading Complete");
        progressBar.setValue(0);
        progressBar.setString("");
        if (embed) {
            getContentPane().setVisible(false);
        } else {
            setVisible(false);
        }
    }

////////////////////////////////Static Methods//////////////////////////////////
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        AreWeThereYet test = new AreWeThereYet(null);
        int size = 100000;

        test.loadingStarted(size, "Test 1");
        for (int i = 0; i < size; i++) {
            test.loadingProgress();
        }
        test.loadingComplete();
        test.loadingStarted(size * 5, "Test 2");
        for (int i = 0; i < size * 5; i++) {
            test.loadingProgress();
        }
        test.loadingComplete();
        System.exit(0);
    }
/////////////////////////////////GUI Components/////////////////////////////////

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Loading");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(143, 141, 141));
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        setResizable(false);
        setUndecorated(true);

        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("Finished Loading");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
////////////////////////////////////////////////////////////////////////////////

